### ISSUE TITLE
Minor Optimisation

### ISSUE THREAD

**Issue by Arcticon** [Pita/berlin-vac-appointment-checker#1]
https://github.com/Pita/berlin-vac-appointment-checker/blob/40fa6b16e37fce90377bfdf52f7e3ce270531908/demon.js#L134-L177

What about moving the lookup table to a ES6 Map and just check if `stat.id` exists and is in that list, then open that link and set isOk true. Would make the lookup table much easier to maintain :)

Something like:

`const lookupTable = new Map([
    ['arena', 'https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158431']
])`
followed by

`if(stat && stat.id && lookupTable.has(stat.id)){
    isOk = true;
    open(lookupTable.get(stat.id));
}`

**Comment by Pita** [comment]
Yes that's true. At the beginning I wanted to filter for certain vaccination centers. That's why there is this isOk flag. It's not necessary anymore, or could be solved with a lookup map, yes

**Comment by Arcticon** [comment]
Do you want me to create a PR?

You can check the code here: https://github.com/Arcticon/berlin-vac-appointment-checker/commit/02ac82807b3277c871a7650dd6401495b416e83f

**Comment by Pita** [comment]
I merged it, thank you!
