### ISSUE TITLE
"Besuchungsgrund" filter

### ISSUE THREAD

**Issue by gerasy** [Pita/berlin-vac-appointment-checker#12]
It constantly opens up tabs with where the only available appointments have "Besuchungsgrund" that has nothing to do with "impfung"
![image](https://user-images.githubusercontent.com/5672529/120792319-9e9d9c80-c535-11eb-8980-0a25a994306c.png)

**Comment by mousemke** [comment]
sadly we're fairly limited by the api that we can detect openings in specific reasons (meaning we are detecting only open covid vaccine appointments) but we cannot open the page to the specific visit reason, we can only go the the main page of the location.

what i assume is happening is the vaccination appointments are being detected, and the page is being opened, and by the time it gets to the page and to the right reason, the appointment is gone. the fact that other modes show appointments is purely coincidental.

to doublecheck / show this, i have added a debug mode in the config. this does not add any functionality for looking for appointments, only for showing that it's working correctly.
